integrate openshift route plugin with rollouts manager
argoproj-labs/argo-rollouts-manager pull request #15
Opened 2023-12-07 08:06 UTC by ishitasequeira

Integrate [Openshift Route Plugin](https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-openshift) with RolloutsManager.

2023-12-07 08:36 UTC, ishitasequeira commented on controllers/configmap.go
> +			Location: "",
Need to add the https url here.

2023-12-07 10:31 UTC, anandf commented on controllers/configmap.go
> +	actualConfiMap := &corev1.ConfigMap{}
typo

2023-12-07 10:33 UTC, anandf commented on controllers/default.go
> +	OpenshiftRolloutPluginName = "openshift-route-plugin"
Should it be `OpenShift` ?

2023-12-07 12:58 UTC, anandf requested changes
posted some minor comments. Otherwise looks ok to merge

2023-12-10 09:05 UTC, ishitasequeira commented on api/v1alpha1/argorollouts_types.go
> +	DisableRoutePlugin bool `json:"disableRoutePlugin,omitempty"`
I like the idea of having a way to extend plugins. I am thinking of below format in that case, let me know what you think.

```
plugins:
    - name: openshift-route-plugin
      enabled: true
      localtion: https://example.com/path/to/rollout-plugin-traffic-controller # if no path is provided, default would be picked from `/plugin` directory.
```

Also, I would like to know how do we prioritize the location value details as users can also change this value in ConfigMap. In the current implementation, we are creating a ConfigMap (if not present already) and updating the ConfigMap with the plugin location only if the ConfigMap does not already contain the plugin name and location. If the plugin information is already present, we do not make any changes (i.e. do not update the location). By adding the location to the rollout-manager spec, how do we prioritize which location value gets picked up?

2024-01-03 14:41 UTC, anandf approved these changes

2024-01-05 11:36 UTC, iam-veeramalla approved these changes
/lgtm 
Thanks @ishitasequeira

2024-01-05 16:14 UTC, merged