Add ginkgo tests for congigMaps
argoproj-labs/argo-rollouts-manager pull request #40
Opened 2024-02-15 10:38 UTC by Rizwana777

**What does this PR do / why we need it**:
- Ginkgo tests for configMaps

**Which issue(s) this PR fixes**:
Fixes #? Issue #15 and Issue #25

2024-02-21 08:00 UTC, jgwest requested changes
In addition, I happened to notice that plugin download doesn't work on OpenShift (unfortunately we're not running the E2E tests against OpenShift, so it doesn't automatically catch this yet :sweat_smile:). It would be good to fix it is as part of this PR. To reproduce:

1) Log in to OpenShift cluster from clusterbot (e.g. `rosa create 4.14`)
2) In rollouts manager dir, run `hack/run-upstream-argo-rollouts-e2e-tests.sh`

You will see it gets stuck on this step:
```
+ kubectl get -n argo-rollouts deployment/argo-rollouts
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
argo-rollouts   0/1     1            0           0s
+ kubectl wait --for=condition=Available --timeout=10m -n argo-rollouts deployment/argo-rollouts
```


If you look at the logs of the `argo-rollouts` Pod, you will see the error:

```
[jgw@localhost-lan argo-rollouts-manager]$ k logs argo-rollouts-65b44974f6-6n9dl
time="2024-02-21T06:55:05Z" level=info msg="Argo Rollouts starting" version=v1.6.6+737ca89
time="2024-02-21T06:55:05Z" level=info msg="Using namespace argo-rollouts"
time="2024-02-21T06:55:05Z" level=info msg="GET https://172.30.0.1:443/api/v1/namespaces/argo-rollouts/secrets?labelSelector=istio.argoproj.io%2Fprimary-cluster%3Dtrue&limit=1 200 OK in 27 milliseconds\n"
time="2024-02-21T06:55:05Z" level=info msg="GET https://172.30.0.1:443/version 200 OK in 1 milliseconds\n"
time="2024-02-21T06:55:05Z" level=info msg="Creating event broadcaster"
time="2024-02-21T06:55:05Z" level=info msg="Setting up event handlers"
time="2024-02-21T06:55:05Z" level=info msg="Setting up experiments event handlers"
time="2024-02-21T06:55:05Z" level=info msg="Setting up analysis event handlers"
time="2024-02-21T06:55:05Z" level=info msg="GET https://172.30.0.1:443/api/v1/namespaces/argo-rollouts/configmaps/argo-rollouts-config 200 OK in 10 milliseconds\n"
time="2024-02-21T06:55:05Z" level=fatal msg="Failed to download plugins: failed to create plugin folder for plugin (argoproj-labs/openshift-route-plugin): (mkdir /home/argo-rollouts/plugin-bin: permission denied)"
```

To fix this, in `deployment.go`, you can probably modify our generation of the Deployment, so that the Deployment contains the following volumeMounts/volume fields:

```
kind: Deployment
  name: # (...)
  namespace: # (...)
spec:
  containers:
  - name: argo-rollouts
    volumeMounts:
    - mountPath: /home/argo-rollouts/plugin-bin
      name: tmp
  volumes:
  - emptyDir: {}
    name: tmp
```

2024-02-22 13:40 UTC, Rizwana777 commented on controllers/configmap_test.go
> +			"trafficRouterPlugins": string(pluginString),
Done

2024-02-22 13:40 UTC, Rizwana777 commented on controllers/deployment_test.go
> +	It("should update the deployment if it already exists", func() {
Yes agreed, Updated tests

2024-03-05 15:41 UTC, jgwest approved these changes
LGTM, thanks @Rizwana777!

2024-03-05 15:41 UTC, merged