Fix '.spec.additionalMetadata' field issue where is is not updating labels/annotations of existing rollouts resources
argoproj-labs/argo-rollouts-manager pull request #76
Opened 2024-07-23 12:07 UTC by Rizwana777

JIRA - https://issues.redhat.com/browse/GITOPS-4779

2024-07-25 20:19 UTC, jgwest requested changes

2024-07-25 20:19 UTC, jgwest commented on controllers/utils.go
> +		if _, exists := obj.Labels[k]; !exists {
I think the implementation of this function is buggy as provided, here's how I think it should work. Hopefully unit tests (mentioned above) will verify this.

```go
// removeUserLabelsAndAnnotations will remove any miscellaneous labels/annotations from obj, that are not used or expected by argo-rollouts-manager. For example, if a user added a label, "my-key": "my-value", to annotations of a Role that is created by our operator, this function wouls remove that label from 'obj'.
func removeUserLabelsAndAnnotations(obj *metav1.ObjectMeta, cr rolloutsmanagerv1alpha1.RolloutManager) {

	defaultLabelsAndAnnotations := metav1.ObjectMeta{}
	setRolloutsLabelsAndAnnotationsToObject(&defaultLabelsAndAnnotations, cr)

	for objectLabelKey := range obj.Labels {

		existsInDefault := false

		for defaultLabelKey := range defaultLabelsAndAnnotations.Labels {

			if defaultLabelKey == objectLabelKey {
				existsInDefault = true
				break
			}
		}

		if !existsInDefault {
			delete(obj.Labels, objectLabelKey)
		}

	}

	for objectAnnotationKey := range obj.Annotations {

		existsInDefault := false

		for defaultAnnotationKey := range defaultLabelsAndAnnotations.Annotations {

			if defaultAnnotationKey == objectAnnotationKey {
				existsInDefault = true
				break
			}
		}

		if !existsInDefault {
			delete(obj.Annotations, objectAnnotationKey)
		}
	}

}
```

2024-07-26 10:58 UTC, Rizwana777 commented on controllers/resources_test.go
> +		It("Verify whether existing labels are not getting removed from resources", func() {
yes, some CRs need to to be passed in the functions,` err = r.reconcileRolloutsClusterRoleBinding(ctx, clusterRole, serviceAccount, a)` like this, I have break the tests and moved the repeated CRs to a generic function

2024-07-31 05:01 UTC, jgwest approved these changes
LGTM, thanks @Rizwana777!

2024-07-31 05:01 UTC, merged